version: "3.9"

services:
  backend:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    container_name: blog-backend
    tty: true
    stdin_open: true
    restart: always
    ports:
    - 8000:8000
    volumes:
    - ./:/srv/project
    depends_on:
      - memcache
      - postgres
      - rabbitmq
    env_file:
      - .env

  memcache:
    image: memcached:1.6.9
    container_name: blog-memcache
    tty: true
    stdin_open: true
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: blog-rabbitmq
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
    ports:
    - 15672:15672

  postgres:
    image: postgres:12
    container_name: blog-db
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
    ports:
    - 5432:5432


